### ISSUE TITLE
Upgrade page can be confusing to users

### ISSUE THREAD

**Issue by Framb75** [nabaztag2018/pynab#102]
Ears driver indique 3 mises à jour  mais le bouton d'interface web reste grisé.

https://www.tagtagtag.fr/forum/showthread.php?tid=117

**Comment by pguyot** [comment]
Even when there is no change on pynab (release or master branch), there can be changes on drivers, yet the upgrade button is (on purpose) not available.

Several users have been confused by this interface.

**Comment by sanderant** [comment]
So is it correct that it only updates pynab and not the drivers?

**Comment by pguyot** [comment]
Update button runs pynab's upgrade script which updates everything, but is only available when there is something to update for pynab.
We should get pynab's release branch to stick to specific commits or branches of the other projects.

**Comment by pguyot** [comment]
Cf also #122
