### ISSUE TITLE
Mastodon is missing after pairing nabaztag's ears

### ISSUE THREAD

**Issue by Framb75** [nabaztag2018/pynab#103]
Mastodon is gone even after reboot.

https://www.tagtagtag.fr/forum/showthread.php?tid=116

**Comment by nguillaumin** [comment]
I had this issue and found a possible cause: When pairing with another rabbit the identifier should be `name@instance.tld`, **without** the leading `@` (e.g. NOT `@name@instance.tld`).

[This](https://github.com/nabaztag2018/pynab/blob/master/nabmastodond/templatetags/mastodon_tags.py#L9) does not cater for multiple `@`, and that's causing a crash. The values are written in the DB though, so it's too late and it cannot be recovered after that (I'm not sure why the Mastodon panel disappears from the web interface though). Only way I found was to `DELETE FROM nabmastodond_config`. So hopefully making that code a bit more defensive may fix the issue.
