### ISSUE TITLE
Set distinct wake-up/sleep times per day

### ISSUE THREAD

**Issue by supermomo31** [nabaztag2018/pynab#104]
Would it be possible to manage the alarm clock, Wake up time per day of the week?

**Comment by pguyot** [comment]
And also add an option to play "wake-up" sounds.

**Comment by supermomo31** [comment]
the Wake up sound could be the 4 - 5 first steps of "Day of tentacle" opening themes. That would be fun!

**Comment by f-laurens** [comment]
To be closed as resolved by #125.
