### ISSUE TITLE
Add option to disable sound signature for nabsurprised

### ISSUE THREAD

**Issue by kymodoke** [nabaztag2018/pynab#109]
Would it be possible to add an option to disable sound signature for nabsurprised (for instance as a setting item at user's discretion with a tick box on web GUI) ?

Some users would prefer to get the rabbit to speak more spontaneously, without "ding-dong" before and after its sentences.

*I did manage to do it manually by just commenting the signature call on pynab/nabsurprised/nabsurprised.py file, but it's not a permanent thing nor something easy to do for everyone.*

Thanks

**Comment by pguyot** [comment]
Signature are an important part of Nabaztag and they are unlikely to go away.
