### ISSUE TITLE
RFID PPIC non géré

### ISSUE THREAD

**Issue by Smaky07** [nabaztag2018/pynab#117]
J'ai pas mal de tag RFID reconnus mais inutilisables. Voici un UID posant problème : d0:02:0c:c1:1e:cb:0d:02

Si je peux donner plus d'information (pas ce week end mais la semaine prochaine), je suis disponible.

En pièce jointe une photo de ce que à quoi ils ressemble.

Ils fonctionnais très bien avec le nabaztag original et permettait de lancer des MP3s.

Je n'ai pas encore eu le temps de vérifier si il était possible d'écrire dedans.

![20200221_170538](https://user-images.githubusercontent.com/22472438/75050636-a2d2b180-54cc-11ea-8031-d8e5927d6306.jpg)

**Comment by pguyot** [comment]
Il semble que ce soit un tag SRIX4K de Motorola si j'ai bien décodé le UID.
On a la datasheet, je peux ajouter le support et vous laisser essayer ?

**Comment by Smaky07** [comment]
Je pourrais tester à partir de dimanche soir pas soucis. Je suis sur la branche Master.

**Comment by Smaky07** [comment]
C'est bon pour moi. mes 10 tags SRIX4 sont OK.

**Comment by pguyot** [comment]
Merci.
