### ISSUE TITLE
Mastodon label incorrect

### ISSUE THREAD

**Issue by klorydryk** [nabaztag2018/pynab#129]
On the first page of nabaztag.local, we can register a mastodon account. The address displayed is not exactly correct :

> Name
> Name@Name@servername

It should be 
> @Name@servername

Pynab Version v0.7.4
Version GNU/Linux 10 (buster), issue 2019-09-26

**Comment by f-laurens** [comment]
Shouldn't this issue be closed?
It doesn't seem anymore applicable to current Pynab release (v0.8.4), where Mastodon account address is displayed correctly:
> `Name`
> `name@server`
