### ISSUE TITLE
API curl call external from Pi zero

### ISSUE THREAD

**Issue by damien-reveillon** [nabaztag2018/pynab#134]
Hello,
The goal is simple make a curl request to use the service already developp within pynab.( play a sound, move an ears, ...)
The file https://github.com/nabaztag2018/pynab/blob/master/PROTOCOL.md is clear about the structure of the call (JSON).
But i don't manage to make it work.
Please see my last try:
curl -i -X PUT -H "Content-Type:application/json" -d '{"type":"ears","left":1,"right":5}' IP:8080/api/command
Do you know what i'm missing?
Damien

**Comment by BoOsteous** [comment]
Hi, the existing API in NABD is not REST, it will unfortunatly not work with CURL. 
You can look at this forum thread : https://www.tagtagtag.fr/forum/showthread.php?tid=207
