### ISSUE TITLE
Pynab logs not rotated

### ISSUE THREAD

**Issue by f-laurens** [nabaztag2018/pynab#139]
Logs for Pynab services are currently not rotated.
For long running rabbits, this may lead to suffocation due to file system saturation.

Suggestion:  implement log rotation by installing a file **/etc/logrotate.d/pynab** with contents similar to:
```
 /var/log/nab*.log
 {
         daily
         rotate 7
         missingok
         notifempty
         copytruncate
         delaycompress
         compress
 }
```

**Comment by 232enero** [comment]
Very good idea! Thanks!

**Comment by f-laurens** [comment]
Note: file installed in **/etc/logrotate.d** should belong to ```root```, not ```pi```, otherwise it is ignored by ```logrotate ```service.
