### ISSUE TITLE
Missing admin/info web interface

### ISSUE THREAD

**Issue by pguyot** [nabaztag2018/pynab#15]
The web interface should display some admin information about the status of the Pi: installed version, network info, hostname, etc. and allow some basic operations avoiding SSH access.

See also #12

**Comment by mehdichaouch** [comment]
One other project also in Python, for Raspberry, with a nice admin/info features is [OctoPrint](https://github.com/OctoPrint/OctoPrint), maybe part of code could be duplicate like the shutdown/restart menu.
What di you think ?

**Comment by f-laurens** [comment]
> One other project also in Python, for Raspberry, with a nice admin/info features is [OctoPrint](https://github.com/OctoPrint/OctoPrint), maybe part of code could be duplicate like the shutdown/restart menu.
> What do you think ?
No need to duplicate here, since shutdown/restart was already implemented in PR #126.

**Comment by mehdichaouch** [comment]
As I see in http://nabaztag.local/system-info/ missing issue elements are :
- network info
- hostname

That's right?

**Comment by f-laurens** [comment]
Shouldn't this issue considered closed now by #126 #185 #190?
