### ISSUE TITLE
Ear position ‘unknown’ - hardware problem?

### ISSUE THREAD

**Issue by srcshelton** [nabaztag2018/pynab#151]
Under `System Information` -> `Hardware` I see listed:

```
Left ear	ok (position unknown)
Right ear	ok (position=10)
```

... is this normal, or does this indicate a software or hardware issue?

Running the Ears Hardware test doesn't seem to change things at all.

Is there anything I can do to diagnose or fix?

**Comment by f-laurens** [comment]
This is a hardware issue with the ear motor/mechanism. The hardware test will only confirm the problem.

This type of question should rather be raised on the appropriate Tagtagtag forum:  [https://www.tagtagtag.fr/forum/](url)
This issue should be closed.

**Comment by srcshelton** [comment]
Okay, thanks!
