### ISSUE TITLE
0.82 Raspberry Led ON

### ISSUE THREAD

**Issue by a-mnt** [nabaztag2018/pynab#156]
Since the installation of 0.82 the led of my raspberry has been continuously lit

**Comment by f-laurens** [comment]
Is it related to 8.0.2 itself?
If the Raspberry Pi kernel has been upraded (from 4.19 to 5.4), the code to turn off the LED (in nabboot.py) needs to be fixed.
See: [Fix system LED setup for Raspberry Pi kernel 5.4.](https://github.com/f-laurens/pynab/commit/c96a1e4003882c6a2caea2a2cd13b9e85cd780fb)

**Comment by Nicosss** [comment]
Thanks, the fix turns off the led with the kernel 5.4.51+.
Need to be integrated in pynab release with kernel 5.4.
