### ISSUE TITLE
Web interface lacks documentation/help

### ISSUE THREAD

**Issue by pguyot** [nabaztag2018/pynab#16]
Typically, information led patterns (e.g. for the weather service) should be documented on the website.

**Comment by sanderant** [comment]
The current help page just links to https://tagtagtag.fr/help.html which is pretty sparse. It makes more sense to host some of the documentation locally, maybe have a link to the the internet as fallback in the event things change again.

The advantage of this approach would be that the help would be relevant to that version of the software in the event you don't update or choose not to.

Let's start with the led patterns. :) I'm not sure if I should be worried with yellow dots and pink underneath!

**Comment by f-laurens** [comment]
Weather forecast LEDs patterns help may presumably be 'stolen' from https://www.tagtagtag.fr/weather.html
But do we have somewhere some documentation for:

- rain alert patterns;
- air quality patterns.

**Comment by mehdichaouch** [comment]
I asked the same question for air quality pattern, in [discussions#227](https://github.com/nabaztag2018/pynab/discussions/227), but it was deleted 🤔 😢

@pguyot what do you think about adding a folder `docs` folder for package reference documentation and moving weather documentation there?

**Comment by nabaztag2018** [comment]
Here is the animation for rain alert (video), i'm going to ask Antoine for Air quality pattern.

https://user-images.githubusercontent.com/44699852/118674616-38591000-b7fa-11eb-938a-174ad9d7d99f.mp4

**Comment by f-laurens** [comment]
> Here is the animation for rain alert (video)

Thanks. The same converted to GIF (to have same format as weather forecast patterns):
![pluie1h](https://user-images.githubusercontent.com/33164641/118684340-6d696080-b802-11eb-963f-5f28ec629951.gif)

**Comment by mehdichaouch** [comment]
> Thanks. The same converted to GIF (to have same format as weather forecast patterns):

Thanks, The same in square ratio
![nabaztag-air-quality](https://user-images.githubusercontent.com/861701/118713051-ceecf780-b821-11eb-952d-47cbf85a83ce.gif)

**Comment by f-laurens** [comment]
> i'm going to ask Antoine for Air quality pattern.

Any progress on this?
