### ISSUE TITLE
Plea to merge outstanding PRs...

### ISSUE THREAD

**Issue by f-laurens** [nabaztag2018/pynab#176]
This is a plea from an humble contributor to the maintainers of this repository
to merge some pull requests that have been outstanding for several months now and are more than ripe for integration...

In particular the following (not all mine 😉): PR #185 , PR #157 , PR #164 , PR #180 ,
which I have all thoroughly tested in my fork (see https://github.com/f-laurens/pynab/releases/tag/v0.8.4-fl).

**Comment by nabaztag2018** [comment]
Yes ! Sorry for this long long long delay, I'm working on it !

**Comment by mehdichaouch** [comment]
@nabaztag2018 only one remaining PR https://github.com/nabaztag2018/pynab/pull/126 to close this issue...

**Comment by f-laurens** [comment]
This issue can now be closed AFAIAC...
