### ISSUE TITLE
Weather forecast should be played at predefined times

### ISSUE THREAD

**Issue by pguyot** [nabaztag2018/pynab#18]
Weather forecast are currently only played when using ASR or the button on the web interface.
It lacks the ability to program forecast at predefined times.

**Comment by f-laurens** [comment]
Shouldn't this issue considered closed by https://github.com/nabaztag2018/pynab/commit/447024610631ee1fa4b6bdeed68585c57df96f90 which roughly does the job (forecasts at regular intervals)?
