### ISSUE TITLE
Weather is not automatically configured

### ISSUE THREAD

**Issue by pguyot** [nabaztag2018/pynab#209]
At least in Paris.
Required for #208.
<img width="990" alt="Screenshot 2021-05-08 at 10 12 42" src="https://user-images.githubusercontent.com/168407/117532078-14b9ec80-afe6-11eb-9652-56b8010f6ab0.png">

**Comment by f-laurens** [comment]
Would it be useful/feasible to preload the Pynab DB on the release image with a snapshot (see [backup/restore_pynab_db](https://github.com/f-laurens/pynab_cli/tree/release#backuprestore_pynab_db)) containg reasonable defaults? like **:**
- no chime hours / sleep/wake-up times
- low Tai chi/Surprise frequency
- 8 Ball guru off
- Paris (**obviously!**) as location for Weather / Air quality, visual animations enabled
- locale: **fr** or **en** ?
