### ISSUE TITLE
Clicking chatouille doesn't seem to work after first boot

### ISSUE THREAD

**Issue by pguyot** [nabaztag2018/pynab#210]
When starting from the releng image.
Restarting nabsurprised from SSH fixed the problem.
The same behavior can be observed with tai chi.

**Comment by f-laurens** [comment]
Cannot reproduce this behaviour with an existing (v8.0.4) image upgraded to to `latest` state of releng branch:
nabsurprided and nabtaichid are responsive after boot.
Could it be related to the specific actions performed after initial boot?
