### ISSUE TITLE
Nightly Builder workflow should not fail when there are no old builds to remove / should remove tags for removed builds

### ISSUE THREAD

**Issue by f-laurens** [nabaztag2018/pynab#253]
(see https://github.com/nabaztag2018/pynab/runs/2680683144?check_suite_focus=true)
The case where there are less than _keep_ existing builds should be handled properly.

**Comment by f-laurens** [comment]
Also the `hub release` command used in the 'remove' step does not appear to work correctly in a clone  repository:
it does not operate on the releases in the origin (clone) repository, but on the ones in the upstream (nabaztag2018) repository.

**Comment by mehdichaouch** [comment]
> Also the `hub release` command used in the 'remove' step does not appear to work correctly in a clone repository:
> it does not operate on the releases in the origin (clone) repository, but on the ones in the upstream (nabaztag2018) repository.

If I refer to your fork, the delete [worked](https://github.com/f-laurens/pynab/runs/2698939662?check_suite_focus=true#step:3:8) ?

**Comment by f-laurens** [comment]
> If I refer to your fork, the delete [worked](https://github.com/f-laurens/pynab/runs/2698939662?check_suite_focus=true#step:3:8) ?
The behaviour of the `hub release` command seems weird: it looks like `hub release `(list) operates on the upstream repository, but `hub release delete` operates on the origin repository.

**Comment by mehdichaouch** [comment]
> Have you tested the behavior in your own fork?

Yes and it worked well.

To test, you can create some fake releases with the name pattern: `nightly-` and see tomorrow.

**Comment by f-laurens** [comment]
This issue may be closed since both issues (error when no old builds to remove, and non removal of associated tags) are now fixed in PR #271.
