### ISSUE TITLE
Update GitHub workflows that build/test image to use latest Raspberry Pi OS Lite base image

### ISSUE THREAD

**Issue by f-laurens** [nabaztag2018/pynab#258]
Depends on https://github.com/pguyot/arm-runner-action/pull/2.

**Comment by mehdichaouch** [comment]
Nice idea, but one thing to see before changing is the final size of the pynab image, because GitHub [release max size is 2.0 GB](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas).

**Comment by f-laurens** [comment]
> because GitHub release max size is 2.0 GB

This is something we will have to continue coping with anyway...

> but one thing to see before changing is the final size of the pynab image

Well, the only way to know is to try, and check **after** changing if it still fits the 2.0GB limit...

Another benefit for us of using the latest base image is that it would somewhat reduce build times when creating the Pynab image from this base image, since the `apt update/install ` steps would have less packages to upgrade and run faster.
