### ISSUE TITLE
Hourly announcement for 16:00 is played at 17:00 

### ISSUE THREAD

**Issue by srcshelton** [nabaztag2018/pynab#287]
**Version of pynab:** v0.9.1

**Version of Nabaztag:**

- [ ] Nabaztag (v1)
- [x] Nabaztag:Tag (v2)

**Version of TagTagTag:**

- [ ] Maker Faire 2018
- [x] Ulule 05/2019

**The problem**

Since upgrading from v0.8.4 to v0.9.1, I’ve noticed that the hourly announcement played at 17:00 is the 16:00 one.  Other hours (certainly 18:00) seem to be correct (or, at least, I’ve not noticed any issue).

**Expected behavior**

17:00 announcement played at 17:00, instead of 16:00 announcement.

**Comment by srcshelton** [comment]
(I assumed my time-zone was wrong - but all other hourly announcements do seem to be correct!)

**Comment by mrcroupotin** [comment]
In which language speak your rabbit?

**Comment by f-laurens** [comment]
And what is your timezone?

**Comment by pguyot** [comment]
Well spotted!
I am wondering if this file was wrong with the original server code. Anyway, I don't think it is new to release 0.9.1.
