### ISSUE TITLE
Install/CI issue with Kaldi archives

### ISSUE THREAD

**Issue by f-laurens** [nabaztag2018/pynab#339]
The archives for the e4940d045 Kaldi release (https://github.com/pguyot/kaldi/releases/download/e4940d045/kaldi-e4940d045-linux_raspbian10-armv6l.tar.xz  and https://github.com/pguyot/kaldi/releases/download/e4940d045/kaldi-e4940d045-linux_raspbian11-armv6l.tar.xz) seem to be currently unreachable:
This causes the Pynab install.sh script to fail when downloading the archive (404 error on wget),
and the CI test and build workflows to fail when running the install.sh script.

**Comment by pguyot** [comment]
Links still yield 404s. Seems like a Github issue to me. Did file a ticket (#1627840)

**Comment by f-laurens** [comment]
Problem apparently fixed. Closing...
