### ISSUE TITLE
Update page only displays pynab status

### ISSUE THREAD

**Issue by nabaztag2018** [nabaztag2018/pynab#388]
<img width="1220" alt="Capture d’écran 2022-06-12 à 13 59 08" src="https://user-images.githubusercontent.com/44699852/173232073-80e031be-6e17-4743-929f-958a8e5fe8c7.png">

**Comment by pguyot** [comment]
Probably related to new installation directory

**Comment by nabaztag2018** [comment]
It happens both in the update of 0.9.1 (home directory /home/pi) and a fresh build (/opt/pynab)

**Comment by f-laurens** [comment]
> Probably related to new installation directory

Or rather to changes in https://github.com/nabaztag2018/pynab/commit/d5267708251881a553d185621c9e8c0e0230dad8.
