### ISSUE TITLE
Ears driver broken on v1.0.0 images

### ISSUE THREAD

**Issue by f-laurens** [nabaztag2018/pynab#394]
Ears driver is missing (incorrect build missing `tagtagtag-ears.dtbo` file) on v1.0.0 images that use the 5.15 kernel (non-Raspbian images).
See https://github.com/pguyot/tagtagtag-ears/issues/10 and https://github.com/nabaztag2018/pynab/runs/6866385019?check_suite_focus=true build traces:
`make: *** No rule to make target 'tagtagtag-ears.dtbo', needed by 'install'.  Stop.`

**Comment by f-laurens** [comment]
It this point, it would be safer to remove the non-Raspbian images from [v1.0.0](https://github.com/nabaztag2018/pynab/releases/tag/v1.0.0), till problem is fixed and the images are regenerated.

**Comment by nabaztag2018** [comment]
Yes you're right. We'll correct that later. Thanks !

**Comment by f-laurens** [comment]
Note: the dietpi image should also be removed.

**Comment by f-laurens** [comment]
It would be nice to fix this ASAP (at least fix https://github.com/pguyot/tagtagtag-ears/issues/10 now, even if new v1.0.0 images  are  not regenerated).

**Comment by f-laurens** [comment]
Closing, since https://github.com/pguyot/tagtagtag-ears/issues/10 is now fixed.
