### ISSUE TITLE
Turn off the rPi Zero LED

### ISSUE THREAD

**Issue by 232enero** [nabaztag2018/pynab#40]
The rPi Zero Power LED should be turned off.

Everything is explained here : https://www.jeffgeerling.com/blogs/jeff-geerling/controlling-pwr-act-leds-raspberry-pi

**Comment by pguyot** [comment]
Please note that power LED should be restored on shutdown (from nabboot), as it's a way to know if the power adapter can be unplugged.

**Comment by Lyokovic** [comment]
After testing manually, I think there is no need to switch it on again on shutdown : even disabled in Linux, it will still blink when shutdown is done and it is ready to unplug.

I'll try to make a PR tonight.
