### ISSUE TITLE
NFC tags cannot trigger "gourou" messages

### ISSUE THREAD

**Issue by cyril1929** [nabaztag2018/pynab#407]
- Either add a "gourou" entry in the "application" menu,
- Either add "gourou" entry in the "theme" sub-menu of the "humeur" application.

**Comment by nabaztag2018** [comment]
Very good idea. I'll add it as soon as I'm done with shipping (or if I want to do something else :-))

**Comment by cyril1929** [comment]
Cette fonction n'est pas présente dans la version 1.0.2. J’espère qu'elle le sera dans la prochaine ;-)
