### ISSUE TITLE
Flash partition should be resized at first reboot

### ISSUE THREAD

**Issue by 232enero** [nabaztag2018/pynab#41]
Currently, when installing the Pynab image, the flash partition is not expanded and does not use the full 16GB.
Some info here : https://elinux.org/RPi_Resize_Flash_Partitions

**Comment by 232enero** [comment]
raspi-config --expand-rootfs

**Comment by pguyot** [comment]
Resizing was disabled by sample setup scripts.
Maybe fix this following:
https://www.raspberrypi.org/forums/viewtopic.php?p=1503766#p1503766

**Comment by pguyot** [comment]
Fixed in 0.6.1.
