### ISSUE TITLE
nfc nfc0: st25r391x_turn_field_on: Failed to turn oscillator on: -1

### ISSUE THREAD

**Issue by hpiedcoq** [nabaztag2018/pynab#436]
**Version of pynab:** v1.0.1

Raspbian GNU/Linux 10 (buster) - Kernel 5.10.103+ #1529 armv6l

**Version of Nabaztag:**

- [ ] Nabaztag:Tag (v2)

**Version of TagTagTag:**

- [ ] Ulule 10/2021

**Version of RFID:**

- [ ] Board NFC 2022 from Ulule 10/2021

**The problem**

Upgdraded to 1.0.1 form the web.

dmesg on the rabbit is pretty verbose with error : 

```
[ 6753.736096] nfc nfc0: st25r391x_turn_field_on: Failed to turn oscillator on: -1
[ 6759.665083] nfc nfc0: st25r391x_turn_field_on: Failed to turn oscillator on: -1
[ 6770.474210] nfc nfc0: st25r391x_turn_field_on: Time out waiting for interrupt bit (adjust regulators command)
[ 6780.065285] nfc nfc0: st25r391x_turn_field_on: Failed to turn oscillator on: -1
[ 6783.817033] nfc nfc0: st25r391x_turn_field_on: Failed to turn oscillator on: -1
[ 6784.667080] nfc nfc0: st25r391x_turn_field_on: Failed to turn oscillator on: -1

```

**Comment by f-laurens** [comment]
See issue https://github.com/pguyot/st25r391x/issues/5 ...

**Comment by f-laurens** [comment]
It might be useful to keep this issue open, as a reminder, till NFC driver issue is fixed.
