### ISSUE TITLE
Change in the timezone requires a restart of nabd

### ISSUE THREAD

**Issue by 232enero** [nabaztag2018/pynab#45]
Either correct this or ask the user to reboot the rabbit (--> tell her/him how !)

**Comment by pguyot** [comment]
Confused that it requires to restart nabd, time zone is only used by nabclockd, and nabclockd should cope for time zone adjustments, maybe sleep less than 1 hour between chimes…

**Comment by pguyot** [comment]
Nabclockd actually sleeps for one minute only because I found no way to be waken up by clock adjustments on Python+Linux (typically when clock is adjusted from network time servers).

**Comment by pguyot** [comment]
Trying to reproduce locally. Apparently, nabclockd can skip a chime in some specific timezone update situation.
