### ISSUE TITLE
Sound volume on Nabaztag:tag is too low

### ISSUE THREAD

**Issue by 232enero** [nabaztag2018/pynab#56]
Currently /var/lib/tagtagtag-sound/mixer.conf shows:
`tagtag-speaker-high=112`

Should be 
`tagtag-speaker-high=122`

**Comment by pguyot** [comment]
Fixed in https://github.com/pguyot/wm8960/commit/5ad6f3f0f2e0b9b8fad708dabf47f6c16fe569a5
