### ISSUE TITLE
Error crash nabblockly_server

### ISSUE THREAD

**Issue by 232enero** [nabaztag2018/pynab#67]
Jan  4 18:47:38 nabaztag-master nabblockly[463]: =ERROR REPORT==== 4-Jan-2020::18:47:37.978642 ===
Jan  4 18:47:38 nabaztag-master nabblockly[463]: ** Generic server nabblockly_server terminating
Jan  4 18:47:38 nabaztag-master nabblockly[463]: ** Last message in was {tcp_closed,#Port<0.14>}
Jan  4 18:47:38 nabaztag-master nabblockly[463]: ** When Server state == {state,#Port<0.14>,<<"playing">>,{0,nil},1}
Jan  4 18:47:38 nabaztag-master nabblockly[463]: ** Reason for termination ==
Jan  4 18:47:38 nabaztag-master nabblockly[463]: ** {function_clause,
Jan  4 18:47:38 nabaztag-master nabblockly[463]:        [{nabblockly_server,handle_info,
Jan  4 18:47:38 nabaztag-master nabblockly[463]:             [{tcp_closed,#Port<0.14>},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:              {state,#Port<0.14>,<<"playing">>,{0,nil},1}],
Jan  4 18:47:38 nabaztag-master nabblockly[463]:             [{file,
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                  "/home/pi/pynab/nabblockly/apps/nabblockly/src/nabblockly_server.erl"},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:              {line,78}]},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:         {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:         {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:         {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
Jan  4 18:47:38 nabaztag-master nabblockly[463]: =CRASH REPORT==== 4-Jan-2020::18:47:37.981350 ===
Jan  4 18:47:38 nabaztag-master nabblockly[463]:   crasher:
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     initial call: nabblockly_server:init/1
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     pid: <0.527.0>
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     registered_name: nabblockly_server
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     exception error: no function clause matching
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                      nabblockly_server:handle_info({tcp_closed,#Port<0.14>},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                                                    {state,#Port<0.14>,
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                                                     <<"playing">>,
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                                                     {0,nil},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                                                     1}) (/home/pi/pynab/nabblockly/apps/nabblockly/src/nabblockly_server.erl, line 78)
Jan  4 18:47:38 nabaztag-master nabblockly[463]:       in function  gen_server:try_dispatch/4 (gen_server.erl, line 637)
Jan  4 18:47:38 nabaztag-master nabblockly[463]:       in call from gen_server:handle_msg/6 (gen_server.erl, line 711)
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     ancestors: [nabblockly_sup,<0.439.0>]
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     message_queue_len: 0
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     messages: []
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     links: [<0.453.0>]
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     dictionary: []
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     trap_exit: false
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     status: running
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     heap_size: 2586
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     stack_size: 27
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     reductions: 6504
Jan  4 18:47:38 nabaztag-master nabblockly[463]:   neighbours:
Jan  4 18:47:38 nabaztag-master nabblockly[463]: =SUPERVISOR REPORT==== 4-Jan-2020::18:47:38.053511 ===
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     supervisor: {local,nabblockly_sup}
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     errorContext: child_terminated
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     reason: {function_clause,
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                 [{nabblockly_server,handle_info,
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                      [{tcp_closed,#Port<0.14>},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                       {state,#Port<0.14>,<<"playing">>,{0,nil},1}],
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                      [{file,
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                           "/home/pi/pynab/nabblockly/apps/nabblockly/src/nabblockly_server.erl"},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                       {line,78}]},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                  {gen_server,try_dispatch,4,
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                      [{file,"gen_server.erl"},{line,637}]},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                  {gen_server,handle_msg,6,
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                      [{file,"gen_server.erl"},{line,711}]},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                  {proc_lib,init_p_do_apply,3,
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                      [{file,"proc_lib.erl"},{line,249}]}]}
Jan  4 18:47:38 nabaztag-master nabblockly[463]:     offender: [{pid,<0.527.0>},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                {id,nabblockly_server},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                {mfargs,{nabblockly_server,start_link,[]}},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                {restart_type,transient},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                {shutdown,5000},
Jan  4 18:47:38 nabaztag-master nabblockly[463]:                {child_type,worker}]

**Comment by pguyot** [comment]
Normal behavior of nabblockly. Socket was closed by nabd, probably because it was restarted.
