### ISSUE TITLE
asr / long voice messages makes nabd unable to work

### ISSUE THREAD

**Issue by 232enero** [nabaztag2018/pynab#75]
When a voice message is too long (or sometimes in other situations), the recording of the message does not stop despite the button being release.

After around 90 seconds, we get the libmpg123 error (can't find it...) and nabd is unable to function properly and needs to be restarted.

One fix could be to limit the duration of the voice message to 3 seconds for example.

**Comment by pguyot** [comment]
Probably due to the fact that ASR & NLU uses too much RAM.

**Comment by 232enero** [comment]
Fixed by increasing swap file to 300MB
