### ISSUE TITLE
High CPU usage until I moved the volume wheel

### ISSUE THREAD

**Issue by Lyokovic** [nabaztag2018/pynab#81]
I was testing some code on the nabaztag and it suddently became unresponsive (through ssh).
I saw that the CPU usage was very high, and `tagtagtag-mixerd` with `alsactl` and `rngd` were the most CPU demanding processes for a long time.
Even after reboot there still were this high CPU load. Other services could not work normally.

Just by moving the volume wheel the CPU load dropped and the system became responsive again.

It might be the volume wheel being in a weird position and sending many values overflowing the mixer daemon,

**Comment by pguyot** [comment]
Uhuh. Anything in the logs? Probably /var/log/daemon.log or in dmesg?
Volume button’s driver changes alsa volume on rising GPIO interrupts. Wondering how this could happen while the button is not moved.

**Comment by Lyokovic** [comment]
Yes that was strange. I moved the wheel because I saw the mixer seemed to be related (and I already rolled back my unrelated code changes without any effect).

I did not see any logs in the `dmesg` or in the journal (`journalctl`), apart from the `nabweb` service which could not run normally because of the CPU usage I guess.

**Comment by BoOsteous** [comment]
Hi, i think i had the same issue today, about 6 hours after the upgrade to 7.2.
Not sure this is related to the update but before i did'nt had audio issues, and now i noticed that the sound was cutting a lot.
I saw this post and looked at the processes :
![issue_top](https://user-images.githubusercontent.com/60717987/73889626-6a966680-4870-11ea-9f76-281c53d793e9.JPG)

Then i tried to move the volume down a little down, and everything comes normal again.
Strange !

Will tell you if i can reproduce this issue.

**Comment by f-laurens** [comment]
Has anybody come up with a reproducible test case for this?

**Comment by pguyot** [comment]
Closing this as we failed to reproduce it. Feel free to reopen it if the problem still occurs.
