### ISSUE TITLE
Nabd restarts when rfid driver is not present

### ISSUE THREAD

**Issue by Framb75** [nabaztag2018/pynab#98]
+ echo 'Updating RFID driver - 4/14'
+ '[' -d /home/pi/cr14 ']'
+ cd /home/pi
+ git clone https://github.com/pguyot/cr14
Cloning into 'cr14'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 16 (delta 5), reused 16 (delta 5), pack-reused 0
Unpacking objects: 100% (16/16), done.
+ make
make: *** No targets specified and no makefile found.  Stop.
+ sudo touch /tmp/pynab.upgrade.reboot

After reboot Nabaztag is in loop rebooting again and again.

**Comment by pguyot** [comment]
Thanks for the report!

**Comment by pguyot** [comment]
Your system might be in a stuck state after failed upgrade.
You may want to do:

    cd /home/pi/cr14
    make && sudo make install

**Comment by Framb75** [comment]
was already unstucked but thanks

**Comment by pguyot** [comment]
"After reboot Nabaztag is in loop rebooting again and again." was another bug, which is now also fixed.
